name: product-service
services:
  # Your .NET application service
  api:
    container_name: product-api
    image: product-service-api:latest
    build:
        context: .
        dockerfile: src/ProductService.Api/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      postgres:
        condition: service_healthy
  # PostgreSQL database service
  postgres:
    container_name: product-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: