name: product-service
services:
  # Elastic Search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: Elastic_Search
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shared_network
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: Kibana
    ports:
      - "5601:5601"
    networks:
      - shared_network
  # Your .NET application service
  api:
    image: product-service-api:latest
    container_name: Api
    build:
        context: .
        dockerfile: src/ProductService.Api/Dockerfile
    ports:
      - "8090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - shared_network
volumes:
  postgres-data:
  esdata:
    driver: local
    driver_opts:
      type: none
      device: \xdata\docker\elasticsearch\data
      o: bind

networks:
  shared_network:
    external: true